server:
  port: 9070

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  application:
    name: simple-configuration-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/home/src/sb-demo/sb-demo-config