server:
  port: 9071
  
management:
  context-path: /admin
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    #metadataMap: 
    #  instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
